services:
  api :
    build: ./
    ports:
      - "8000:8000"
    volumes:
       - ./:/app
       - ./temp:/app/temp
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  grafana_data:

networks:
  default:
    driver: bridge
